### ISSUE TITLE
Pluralization is not clear from the docs

### ISSUE THREAD

**Issue by vjpr** [formatjs/react-intl#1019]
I have simple labels such a `Apples` and `Oranges`.

How do I translate these and pluralize them?

The pluralization is separate to the translation phase is it not?

Like if I was only supporting one language I would use a pluralize module, and I'm sure these translations can be automated.

So I want to define in my component `{id: 'apple', howMany: 'many'}`.

If I don't care about messages, is there a simpler way to deal with headings/titles for things?

Here is what I ascertained from the docs:

```js
<FormattedMessage
    id='app.apple'
    description='An apple.'
    defaultMessage='{name, plural}'
    values={{
        name: 'Apple'
    }}
/>
```

But I get this:

```
Module build failed: SyntaxError: [React Intl] Message failed to parse. See: http://formatjs.io/guides/message-syntax/
SyntaxError: Expected "," but "}" found.
```

---

Or should it be this:

```js
defineMessages({
  tractor: {
    id: 'apple',
    defaultMessage: '{apple, plural, one {apple} other {apples}}',
  },

this.props.intl.formatMessage(t.tractor, {tractor: 1})
```

But why should I have to pluralize the English myself? I want that done automatically because there are plenty of libs that can do that...

**Comment by vjpr** [comment]
Okay I fixed it.

I extracted my messages to another file, and was using `defineMessages`, and then trying to use them in `formatMessage`.

**Comment by vjpr** [comment]
But still, if I want to do as I originally said I now have to write

```
const apple = {
    id: 'apple',
    defaultMessage: '{apple, plural, one {apple} other {apples}}',
}

{formatMessage(apple, {item: 2})}
```

to get:

```
apples
```

This is too verbose.

**Comment by papasmile** [comment]
I think you made a fair assessment.  If you **only** want to pluralize using react-intl, what it provides is actually from FormatJS (https://formatjs.io/guides/message-syntax/#plural-format) which is based on ICU formatting (http://userguide.icu-project.org/formatparse/messages).

There is more power in being able to combine pluralization format directly into translations, e.g:
```
en:
{
  "apple": "{apple_amount, plural, zero {none} one {apple} other {apples}}"
}
ar:
{
  "apple": "{apple_amount, plural, zero {ليس} one {تفاحة} other {تفاح}}"
}
```
Instead of three translation nodes for each language there is one in context of the thing being pluralized.

You may be able to find a pluralization library that covers all languages you are interested in or create one and share it :)

**Comment by vjpr** [comment]
@papasmile Thanks. I think the ICU stuff is limiting. From the examples, it seems like its designed for sentences, but I think its more common to use a variety of HTML elements instead of just a string for plurals.

I am going to take a look at `react-i18n` to see if its any better, but it really seems too complicated for me, and adds so much noise to my code.
