### ISSUE TITLE
Add Ordinal Days

### ISSUE THREAD

**Issue by mweiczorek** [formatjs/react-intl#1043]
I can't seem to find anywhere in the API docs how to create ordinal day format (e.g. 1st, 12th). I'm assuming it's not included, so perhaps add this feature?

**Comment by longlho** [comment]
Can u provide an example? Does `selectordinal do what u're looking for`?

**Comment by etaiklein** [comment]
Example: "Jan 1st" instead of "Jan 1"

**Comment by leomotta121** [comment]
in my opinion there could could be just general ordinals formatter.

Example:

"1º" - Brazil
"1st" - US

**Comment by longlho** [comment]
I think this issue is better suited for https://github.com/tc39/ecma402 :)

**Comment by etaiklein** [comment]
> I think this issue is better suited for https://github.com/tc39/ecma402 :)

Sure, but that can take years

**Comment by longlho** [comment]
Because it is not trivial :) 1st we have to figure out whether we have CLDR for it, then come up w/ an API that is somewhat future-proof, otherwise we run into the `RelativeTimeFormat` issue again where we implemented something that isn't compatible with native Intl API.

I just briefly look through and it doesn't look like we have CLDR data for things like `Jan 1st`, which makes it a non-starter. The concept of ordinal days might not be super i18n-safe and you can't just concat strings because that's also not i18n-safe.

On top of that, we don't know if this is a popular enough request to work on, vs other things. If it's popular enough, ECMA-402 is the correct place to propose this kind of thing.

**Comment by leomotta121** [comment]
I mentioned a different situation other than date, just in case it my help anyone I will paste a snippet of what I did:

```javascript
import safeRead from 'safely-read';

import { store } from '~/store';
import globalSuffixes from '~/constants/locales/ordinalSuffixes';

export default function formatOrdinal(number, gender) {
  const { locale } = store.getState().language;
  const pluralRules = new Intl.PluralRules(locale, { type: 'ordinal' });

  return safeRead(
    globalSuffixes,
    [locale, gender, pluralRules.select(number)],
    safeRead(
      globalSuffixes,
      [locale, pluralRules.select(number)],
      null,
      value => `${number}${value}`
    ),
    value => `${number}${value}`
  );
}
```
safeRead just uses lodash.get

**Comment by etaiklein** [comment]
> I mentioned a different situation other than date, just in case it may help anyone I will paste a snippet of what I did:

Thanks! While we wait for an ECMA solution, its really very helpful to have a temporary workaround to solve some of the more common cases.

**Comment by longlho** [comment]
Note that concatenating `1` & `st` doesn't work for all languages and grammar structure so make sure you only do that for the locale you're 100% sure :)

**Comment by leomotta121** [comment]
Yes, I am aware of it, it would take more work to support more languages, I have already researched about en-US, pt-BR, es, es-AR, for those it will work fine
