### ISSUE TITLE
InjectIntl is not updating it's context data or properties of it's wrapper components when we change the intl object in state when we use react-intl-redux along with react-intl

### ISSUE THREAD

**Issue by saikiranraparthi** [formatjs/react-intl#1097]
### Expected behavior
As we update the intl.messages, the  FormattedMessage / intl object throughout the application should update with the new message object.

### Current behavior
When we modify the intl state in the store, the IntlProvider gets the updated messages but not the InjectIntl or the components in the application.

### Step to reproduce for BUG REPORT
Use react-intl along with react-intl-redux. Change the messages object by adding new messages or updating the previous messages with new ones and see if FormattedMessage is updating itself with the new messages or not. Locale is same.

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl-redux` | 0.1.1|
| `npm ls react-intl` | 2.4.0|
| `npm ls react` | 15.6.2|
| `npm --version` | 5.2.0|
| `node --version` | 6.7.0|

| OS | Version |
| --- | --- |
| NAME | VERSION |

| Browser | Version |
| --- | --- |
| NAME | VERSION |

**Comment by yuchi** [comment]
The _IntlProvider_ is known to have issues when you update its configuration.

It is stated right in the documentation that you should pass a key in order to update the language, for example.

I’d suggest you to have some unique id to pass as key to the IntlProvider so that it’s re-rendered.

Pay attention: the whole application gets re-rendered!

**Comment by papasmile** [comment]
Related? https://github.com/yahoo/react-intl/issues/234

**Comment by saikiranraparthi** [comment]
Here, we are not trying to shift between locales.
The problem is, we have 2 or more pages in our application. So, we are initially having the messages related to the landing page. Then, depending upon the navigation, we are trying to get the translations and add them to the intl.messages so that the page renders with its respective messages. So, the locate is same but with more translation messages. Could you please help us in solving this solution. 
Right now, even when we update the store/state, this is not updated in all the components by the InjectIntl though we are able to see that the IntlProvider has the updated messages

**Comment by papasmile** [comment]
@saikiranraparthi don't quite understand what you are trying to do.  Do you perhaps need multiple contexts to get subsets of your translations per context?  look at https://github.com/yahoo/react-intl/wiki/Components#multiple-intl-contexts

It seems unusual to try to manipulate `intl`, since messages can be declared anywhere, e.g. in your component where you use them: https://github.com/yahoo/react-intl/blob/master/examples/translations/src/client/components/locales-menu.js

**Comment by kopax** [comment]
Is this corrected? I have opened #1154 .
