### ISSUE TITLE
[React Intl] Missing locale data for locale: "fr". Using default locale: "en-US" as fallback.

### ISSUE THREAD

**Issue by bakoserge** [formatjs/react-intl#1125]
Hi guys,

being trying for hours to fix the issue above still no luck. Running it in my react-native project.
please help.
Here are the steps I followed as per the documentation:

```
import 'intl';
...
import * as en from 'react-intl/locale-data/en'
import * as fr from 'react-intl/locale-data/fr'
//console.log('fr', fr)
addLocaleData([...fr, ...en]);
```

```
render () {

    return (
      <IntlProvider locale="fr" defaultLocale="en-US">
        <View style={styles.applicationView}>
          <StatusBar barStyle='light-content' />
          <ReduxNavigation />
        </View>
      </IntlProvider>
    )
  }
```

### Your Environment

-react-native

| Executable | Version |
| ---: | :--- |
|`npm Is intl` | ^1.2.5|
| `npm ls react-intl` | ^2.4.0 |
| `npm ls react` | 16.0.0 |
| `npm --version` | 5.6.0 |
| `node --version` | v9.7.1 |

**Comment by papasmile** [comment]
Hi, @bakoserge , can you please tell what error or problem you are having exactly?  Startup logs or console logs or screenshots might help.

**Comment by papasmile** [comment]
Also, I don't know that this library was intended to use with Native.  Check out discussion on https://github.com/yahoo/react-intl/issues/1042

**Comment by bakoserge** [comment]
@papasmile thanks for the reply. 
the error is when I put "en" as the locale I get no error but once I put "fr" I get 
**[React Intl] Missing locale data for locale: "fr". Using default locale: "en-US" as fallback.**
Here is an image of the error below, also thanks for the link to the discussion above, some people did get it to work with react-native which is the same step I am following its just not working leaving me super confused why its working for "en" and nothing else.
![error](https://user-images.githubusercontent.com/1153493/39427070-6164976c-4c50-11e8-8f11-bb7f7bfc2656.png)

**Comment by bakoserge** [comment]
@papasmile 
I got it working finally by importing the locale needed and running addLocaleData in my app.js instead of my RootContainer.
Thanks again for your reply

**Comment by developersnl-omir** [comment]
@bakoserge So why doesn't it work in the RootContainer? I guess you mean index.js (or index.tsx) with RootContainer. It shouldn't behave like that.

**Comment by David-Yuen** [comment]
I'm also having this issue (I think it should be related). I see the error `Missing locale data for locale: "zh-CN"`

My code use to work in 2.4.0, but after upgrading to 2.7.0 it doesn't work anymore.

I have code that dynamically sets the locale and calls addLocaleData(). 

The code looks somewhat like this:

`
let locale = this.getLocaleURL(); //reads url parameter, example: ?locale=zh-CN
let languageCode = locale.split('-')[0];

let loadLocaleData = import(`react-intl/locale-data/${languageCode}`).then(localeData => {
  addLocaleData(localeData);
});

let loadLocaleMessages = import(`locale/${locale}/strings.js`);

let defaultLocaleMessages = import(`locale/${defaultLocale}/strings.js`); //default is en-US

Promise.all([loadLocaleData, loadLocaleMessages, defaultLocaleMessages]).then(values => {
  this.setState({
    locale: locale,
    messages: Object.assign({}, values[2], values[1])
  });
});

then in render method:
return (
  <IntlProvider locale={this.state.locale} messages={this.state.messages}>
    {this.props.children}
  </IntlProvider>
);
`

I'm not sure where the issue is. In the render method, before outputting <IntlProvider>, I put in console.log() messages for this.state.locale and this.state.messages, and they are set properly. 

I'm using a component class Locale in my code, which is called from my index.js file. Something like this:
`
ReactDOM.render(
  <Locale>
    //my component stuff
  </Locale>
, app);
`

For example, i can see `this.state.locale` output `zh-CN`, and `this.state.messages` output an object list of all my messages, such as `{ui.control.ok: "确定"}`. So i'm very sure the locale and messages are set properly. The addLocaleData() should be working properly as well, but something isn't working in 2.7.0, where it did in 2.4.0

But then, i still see the error:
`
[React Intl] Missing locale data for locale: "zh-CN". Using default locale: "en" as fallback.
function.console.(anonymous function)	@	index.js:1452
defaultErrorHandler	@	index.es.js:564
getConfig	@	index.es.js:1000
getChildContext	@	index.es.js:1026
processChildContext	@	react-dom.development.js:9914
invalidateContextProvider	@	react-dom.development.js:9958
finishClassComponent	@	react-dom.development.js:14134
updateClassComponent	@	react-dom.development.js:14069
beginWork	@	react-dom.development.js:14687
performUnitOfWork	@	react-dom.development.js:17242
workLoop	@	react-dom.development.js:17281
renderRoot	@	react-dom.development.js:17359
performWorkOnRoot	@	react-dom.development.js:18252
performWork	@	react-dom.development.js:18159
performSyncWork	@	react-dom.development.js:18132
requestWork	@	react-dom.development.js:18009
scheduleWork	@	react-dom.development.js:17802
enqueueSetState	@	react-dom.development.js:12076
push../node_modules/react/cjs/react.development.js.Component.setState	@	react.development.js:404
`

**Comment by bakoserge** [comment]
@David-Yuen What plateform does it fail on iOS or android?

**Comment by David-Yuen** [comment]
I'm just using a web browser (Google Chrome) on Windows 7 machine. 

I haven't tested this in any other environments

**Comment by emileber** [comment]
Just a heads up for anyone having this problem, depending on your configuration (webpack, babel, etc.), when importing dynamically, the received module data can be nested into a `default` property.

```
import(`react-intl/locale-data/${languageCode}`)
.then(localeData => {
  addLocaleData(localeData.default); // like here for example
});
```

**Comment by indrekru** [comment]
Even simpler, just mock the thing:
`import { IntlProvider, addLocaleData } from 'react-intl';`
and
`addLocaleData({
      locale: 'de',
      pluralRuleFunction: () => {},
    });`

**Comment by ondrejrohon** [comment]
addLocaleData was removed from react-intl 3, what is the correct way to import locales for server side rendered app?

As mentioned in [upgrade guide](https://github.com/formatjs/react-intl/blob/master/docs/Upgrade-Guide.md) I tried to import:
`import '@formatjs/intl-relativetimeformat/dist/locale-data/de';` but I'm getting this log in console: `[React Intl] Missing locale data for locale: "de". Using default locale: "en" as fallback.`

I think this issue should be reopened.

**Comment by longlho** [comment]
Oh for node you have to use native ICU either by compiling or using
full-icu. The upgrade guide should have details on that.

The polyfill would work for node 8/10 but not node 12 because Node12 has
Intl.RelativeTimeFormat already, just by default it doesn’t have locales
other than en

**Comment by jason-yang** [comment]
> 

Just want to say that @emileber answer was the solution for me. If I do an async import, I need to pass the data on with `.default`
