### ISSUE TITLE
FormattedMessage render props do not renders component variables

### ISSUE THREAD

**Issue by darkowic** [formatjs/react-intl#1131]
Hello everyone :)
### BUG REPORT

Components variables passed to `FormattedMessage` used as render props are not rendered.

### Current behavior
```
    <FormattedMessage
      id="welcome"
      defaultMessage={`Formatted message variable as a render props: {variable} You should see this text`}
      values={{ variable: <TextValueComponent /> }}
    >
      {text => text}
    </FormattedMessage>
```
Text will be cut off at `variable` : `Formatted message variable as a render props: `

### Expected behavior
Render it correctly

### Step to reproduce for BUG REPORT
Here is a reproduction case https://codesandbox.io/s/yp8zjow4kx

### Your Environment

| Executable | Version |
| ---: | :--- |
| `npm ls react-intl` | 2.4.0 |
| `npm ls react` | 16.3.2 |
| `npm --version` | 5.6 |
| `node --version` | ~8 |

**Comment by epegzz** [comment]
Having the same issue. Text cuts off at the place where the React component variable would've been rendered. No error messages in console.

**Comment by capndesign** [comment]
+1

Experimenting a bit, it looks like swapping [this line](https://github.com/yahoo/react-intl/blob/master/src/components/message.js#L130) for `return createElement(Fragment, null, ...nodes)` (after importing `Fragment`) fixes it. I assume there is a more elegant solution, but maybe someone will want something brute force-y.

**Comment by edreyyo** [comment]
react-intl seems to be the de facto standard when it comes to React internationalization. Is it still being actively maintained, @ericf?

**Comment by papasmile** [comment]
Please see: https://github.com/yahoo/react-intl/pull/1141#issuecomment-403563027

**Comment by edreyyo** [comment]
Thanks for the link @papasmile. Much appreciated.

**Comment by capndesign** [comment]
I think I figured out why the test passes but the bug is valid! The [documentation](https://github.com/yahoo/react-intl/wiki/Components#formattedmessage) says to use the formatter as @darkowic described in his original post, but the [test](https://github.com/yahoo/react-intl/blob/96a11032768fb3087dcdbe5be0b9e0ba90accb89/test/unit/components/message.js#L267-L292) does it differently.

In that case, the argument is a destructured array of nodes. When I switch to that technique, I was able to find a workable solution.

It seems like the right solution is to update the documentation.
