### ISSUE TITLE
Possible to intentionally not translate for debugging / translating? 

### ISSUE THREAD

**Issue by zocheyado** [formatjs/react-intl#1276]
I am trying to figure out if there is an easy way in react-intl to intentionally display the id of a label instead of the language translation or the fallback. Reason being is I have a large application and sometimes we reuse a key in 20 spots, which makes it really hard for other language who are translating. I am hoping to make react intl display the key rather than the translation so that someone can look at a button and know what key that relates to. I hope that makes sense, any ideas?

**Comment by DragonRaider5** [comment]
You could build an adapter for `defineMessage` in order to drop all default message when you want to.
F.e.:

`/defineMessages.js`
```js
import { defineMessages } from 'react-intl'

const adapter = process.env.SHOW_MESSAGE_IDS !== 'TRUE'
  ? defineMessages
  : function defineMessagesAdapter (messages) {
    messages = Object.keys(messages).reduce(function (result, id) {
      result[id] = {
        ...messages[id],
        defaultMessage: id
      }

      return result
    }, {})

    return defineMessages(messages)
  }

export default adapter
```

Message files
```js
// change
import { defineMessages } from 'react-intl'
// to
import defineMessages from '/defineMessages'
```

I've not tried this and am not sure about how this will impact the stripping done by the babel plugin ⚠️ You'll also need to not provide the translations in order for the default messages (which are now the IDs) to be displayed.

**Comment by DragonRaider5** [comment]
Closing this, as there was no feedback/activity anymore.
I'll happily reopen if there's activity again.
