### ISSUE TITLE
formatRelative return same output for two different output (different month)

### ISSUE THREAD

**Issue by tony-go** [formatjs/react-intl#1391]
Hi Everybody ✋ 

I currently use `formatRelative` in this way : 

Current Behavior :

```javascript
    formatRelative(new Date('2019-05-22T03:24:00')); // output  => '2 month ago'
    formatRelative(new Date('2019-06-20T03:24:00')); // output  => '2 month ago' 
```

Excepted Bahvior 👍 

```javascript
    formatRelative(new Date('2019-05-22T03:24:00')); // output  => '3 month ago'
    formatRelative(new Date('2019-06-20T03:24:00')); // output  => '2 month ago' 
```

That's probably coming from my lack of understanding in the library usage. Let me know :)

My Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 2.8.0 |
|      `npm ls react` | 16.8.6 |
|     `npm --version` | 5.6.0 |
|    `node --version` | 8.11.4 |

| OS   | Version |
| ---- | ------- |
| macOs Mojave | 10.14.5 |

| Browser | Version |
| ------- | ------- |
| Chrome | 75.0.3770.142 |

**Comment by longlho** [comment]
This is due to the fact that month threshold is a lil different and a little non-deterministic tbh. We have a threshold where if you've passed 70% of the month it's considered a new month (or something like that) so this falls into that classification of bugs like:
- Monday to last Friday can either be `4 days ago`, or `last week`.
- Jan to Dec can either be `last month`, or `last year`.

In `react-intl@3` we changed this to `formatRelativeTime` so it behaves closer to how the spec work so this is not an issue in latest beta.
