### ISSUE TITLE
Hyphen in value in message breaks

### ISSUE THREAD

**Issue by JacobBlomgren** [formatjs/react-intl#1398]
In v2 one could have messages like this: `"the year is {current-year}"`, but now they must be `"the year is {current_year}"`, ie no `-` in the value. The error is `SyntaxError: Expected "," but "-" found.`

I don't know if this is a regression, or if it just happened that in v2 it worked but shouldn't have. 

### Step to reproduce for BUG REPORT

`{current-year}` will break but `{current_year}` will not.

```jsx
const App = () => (
  <IntlProvider locale="en" messages={{ example: 'the year is {current-year}'}}>
    <FormattedMessage id="example" values={{
        'current-year': 2019
      }} />
  </IntlProvider>
);
```

Change react-intl back to v2 and it will work

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.0.0 |
|      `npm ls react` | 16.8.6 |
|     `npm --version` | 6.9.0 |
|    `node --version` | 10.16.0 |

**Comment by longlho** [comment]
thanks for reporting, we'll take a look soon

**Comment by longlho** [comment]
cc @pyrocat101

**Comment by pyrocat101** [comment]
Hey @JacobBlomgren,

According to the [documentation][1] of ICU4J, argument name in `MessageFormat` cannot contain `Pattern_Syntax` and `Pattern_White_Space` characters. Here hyphen is a `Pattern_Syntax` character.

With v3 release, we have made breaking changes to the parser so that they are more faithful to the canonical MessageFormat accepted by ICU. Hope that answers your question.

[1]: http://icu-project.org/apiref/icu4j/com/ibm/icu/text/MessageFormat.html

**Comment by longlho** [comment]
I'll add this to the Upgrade Guide as well, thanks for reporting @JacobBlomgren
