### ISSUE TITLE
3.1.7 break compatibility 

### ISSUE THREAD

**Issue by septs** [formatjs/react-intl#1414]
```
TS2741: Property 'intl' is missing in type .....
```

Need to remove the use of `WrappedComponentProps`.

WrappedComponentProps definition:
https://github.com/formatjs/react-intl/blob/79647dae125c5af15ce58afd1899cd6a4c13cd29/src/components/injectIntl.tsx#L28-L30

Affected code:
https://github.com/formatjs/react-intl/blob/ce560e73b159ffd332fa2ded989f12d758b6bb1b/src/components/message.tsx#L43-L45
https://github.com/formatjs/react-intl/blob/ce560e73b159ffd332fa2ded989f12d758b6bb1b/src/components/relative.tsx#L63-L65

**Comment by septs** [comment]
@emmenko @longlho

**Comment by septs** [comment]
Switch React hooks after no need `intl` field inject `intl`
So need to remove the use of `WrappedComponentProps `

**Comment by emmenko** [comment]
Oh boy, sorry about that. I'll spin up another PR. As a follow up we should maybe have more tests in TS, which should hopefully catch those things...

**Comment by emmenko** [comment]
PR is up

**Comment by septs** [comment]
It is recommended to `npm deprecate` this version.

Copy @longlho

**Comment by emmenko** [comment]
In theory yes but it's only affecting TS users. If we do that we should then deprecate other versions as well. So not sure what would be the best approach here.

I think it's enough to mention this in the changelog.

On a related note, we should probably publish to `next` by default instead of `latest`. This will give us some flexibility when releasing and in case of bugs or regressions of `next` versions we can still patch them before promoting them to `latest`.
We're using this approach in my team and it's working great so far.

**Comment by longlho** [comment]
I'm not opposed to `next` but we don't get a whole lot of eyes on `next` unless it's a major release. This bug in particular could have been caught by testing since typecheck would fail (#1416 would address that I believe).
