### ISSUE TITLE
Recent version has broken IE

### ISSUE THREAD

**Issue by mjcampagna** [formatjs/react-intl#1433]
### Expected behavior

App with react-intl dependency should continue to work in IE11.

### Current behavior

App with react-intl dependency crashes in IE11 and below.

### Step to reproduce for BUG REPORT

Import script into app; visit in IE11.

### Your Environment

Internet Explorer 11 and older.

For now, we've rolled back to react-intl 2.9.0, which restores us to a working state in IE.

Have we missed steps someplace for properly upgrading, or was this breaking change unintentional?

**Comment by DragonRaider5** [comment]
Does #1427 maybe solve your issues? `react-intl` now needs to be transpiled by the users.

**Comment by longlho** [comment]
what's the stack trace?

**Comment by damiangreen** [comment]
The debugger breaks here

![image](https://user-images.githubusercontent.com/1592820/65059243-8c4c8b00-d96d-11e9-995d-ff9f07b13da1.png)

**Comment by longlho** [comment]
@damiangreen https://github.com/formatjs/react-intl/blob/master/docs/Getting-Started.md#esm-build should have some instructions on how to fix this

**Comment by arthurgeron** [comment]
It's ironic that in  the doc it's says that it supports IE 11 but also forces you to transpile specifics some libs via workarounds just so it can actually work in the beforementioned browser..

**Comment by arthurgeron** [comment]
Having to transpile react-intl alone adds 30s to my build time

**Comment by PlayMa256** [comment]
```js
module.exports = {
  resolve: {
    mainFields: ['browser', 'main', 'module']
  }
};
```

Might fix the problem as well, where you use the transpiled version rather than the ES module version.

**Comment by smeijer** [comment]
Does anyone know how to get this thing working again with parcel?

**Comment by tgfischer** [comment]
> 
> 
> In your webpack config
> 
> ```js
> module.exports = {
>   resolve: {
>     mainFields: ['browser', 'main', 'module']
>   }
> };
> ```
> 
> Might fix the problem as well, where you use the transpiled version rather than the ES module version.

This worked for me

**Comment by AndreuMad** [comment]
Just import 'react-intl' like that: import *SOMETHING* from 'react-intl/dist';

So just add '/dist'

**Comment by th3fallen** [comment]
I'm actually still getting this same error even after adding your packages to the babel includes.. anyone run into that?

**Comment by arthurgeron** [comment]
@th3fallen  There are other dependencies of react-intl that breaks IE, doing that will also increase your build time significantly, the best solution is to use @playMa256 's suggestion instead.

**Comment by th3fallen** [comment]
@arthurgeron i've actually implemented his suggestion and i still get a syntax error on the same line. pretty confused

**Comment by th3fallen** [comment]
nevermind just needed to update react-intl and that worked. thanks so much

**Comment by janzenz** [comment]
We're experiencing this with `3.11.0`. Following @PlayMa256 solution worked but I'm not sure what the implications of this with other existing libraries we're using. Should we re-open this issue?

**Comment by arthurgeron** [comment]
@janzenz This shouldn't affect other libs, if it does it would break your project during build as it wouldn't be able to find the exported objects properly.

**Comment by smeijer** [comment]
Well, it affects it so much, that you might be importing larger bundles. Legacy bundles are often larger, and not tree-shakeable.

So watching your bundle size before and after that change to your webpack config, might be a wise thing to do.

**Comment by janzenz** [comment]
Thanks @arthurgeron for your response. What I'm wondering about is, how come other libraries (and we have about 30 of them) didn't have to use this option? And we have to specifically use this order of those keys `['browser', 'main', 'module']` and not in the order that [Webpack doc specifies](https://webpack.js.org/configuration/resolve/#resolvemainfields), .e.g. `['browser', 'module', 'main']`

Thank you @smeijer for that info.

**Comment by arthurgeron** [comment]
@janzenz  I completely agree with you, this issue has already been raised [here](https://github.com/formatjs/react-intl/issues/1499#issuecomment-557930677) and  @longlho  stated that "`bundlers’ behaviors are inconsistent`" and that basically it will stay the way it is, even if it means being incompatible (needing extra config) with one of (if not the) most famous bundler (i.e. Webpack).

**Comment by janzenz** [comment]
Thanks @arthurgeron. That led me to find a better solution [resolve.alias](https://github.com/formatjs/react-intl/issues/1499#issuecomment-570151879) option. I find it better than using `resolve.mainFields` because this does not affect the default order of the module imports and it's more explicit. For the benefit of those people finding this thread here is the snippet from that link:

```
module.exports = {
  resolve: {
    alias: {
      "react-intl": path.resolve(
        __dirname,
        "node_modules/react-intl/dist/react-intl.js"
      )
    }
  }
};
```

**Comment by DragonRaider5** [comment]
@arthurgeron To clarify the explanation by @longlho about the definition of the `module` field: The module system is part of the `ES2015` (`ES6`) spec, which is why our entry point given in `module` uses all `ES2105` features. Those are not supported natively by every environment, e.g. IE.

This is why if you want to use it in those environments you'll need to transpile it.

However **Webpack** chose to define it differently:

> The module property should point to a script that utilizes ES2015 module syntax but no other syntax features that aren't yet supported by browsers or node. This enables webpack to parse the module syntax itself, allowing for lighter bundles via tree shaking if users are only consuming certain parts of the library.

[Source](https://webpack.js.org/guides/author-libraries/#final-steps)

The same goes for  **Rollup**:

> `pkg.module` will point to a module that has ES2015 module syntax but otherwise only syntax features that the target environments support.

[Source](https://github.com/rollup/rollup/wiki/pkg.module)

Now it is very vague, what the
> target environments

are. One could argue they are the ones supporting `ES2015`. However you could also argue they are browsers. But where do you do the cut for those?


@longlho should we reconsider our decision based on this findings?

**Comment by tomekit** [comment]
@PlayMa256 Thanks for the: ` mainFields: ['browser', 'main', 'module']` setting in `webpack`.
It resolved my IE11 issues, at least for the dev build: `NODE_ENV=development webpack --mode=development`.

The problem is that now I am getting the: `'exports' is undefined` on all browsers. It fails in `webpack:///node_modules/intl-messageformat-parser/dist/types.js` on line: `Object.defineProperty(exports, "__esModule", { value: true });`

Any idea how to resolve this? 

My webpack:
`var config = {
    devtool: "source-map",
    resolve: {
        extensions: [".js", ".jsx"],
        mainFields: ['browser', 'main', 'module']
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules\/(?!react-intl|intl-messageformat|intl-messageformat-parser)/,
                use: {
                    loader: 'babel-loader',
                }
            }
        ]
    }
};`
