### ISSUE TITLE
FormattedMessage outputs wrong plural form from defaultMessage prop

### ISSUE THREAD

**Issue by fend25** [formatjs/react-intl#1495]
brief example:
https://codesandbox.io/s/react-intl-playground-swb8s

locale: ru

### Expected behavior
When `<FormattedMessage />` used with message id and global messages object passed via provider, it outputs correct plural form.
I expected that `<FormattedMessage />` used with same values object and input string, passed via `defaultMessage` prop, it should output correct plural form.

### Current behavior
In russian language, number 3 assumes a `few` plural form.
`<FormattedMessage />` used input, passed via `defaultMessage` prop, outputs `other` variant for number 3 instead of `few` variant. Formatted message with id (which points to the same string) outputs `few` variant.
The example pretty fine shows the problem: https://codesandbox.io/s/react-intl-playground-swb8s

### Step to reproduce for BUG REPORT

Just follow the link:
https://codesandbox.io/s/react-intl-playground-swb8s

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.3.2|
|      `npm ls react` | 16.10.0|
|     `npm --version` | 6.9.0|
|    `node --version` | 12.4.0|

| OS   | Version |
| ---- | ------- |
| Windows 10 | 17134|

| Browser | Version |
| ------- | ------- |
| Chrome | 77.0.3865.90 |

**Comment by longlho** [comment]
So this is rather complicated/confusing. When there's no corresponding ID in `messages`, we fall back to `defaultMessage`. At this point, there's no guarantee that `defaultMessage` is actually in the language specified by `locale` (`ru` in this case), thus we assume `defaultMessage` is in the language specified by `defaultLocale` (`en` in the case). In order to fix this u can set `defaultLocale="ru"` in the Provider.

This is the same reason why `defaultFormats` is specified separately. The whole `default` logic hierarchy is rather complicated.

cc @redonkulus should we revise this?

**Comment by fend25** [comment]
@longlho thank you so much! it solved my case.
