### ISSUE TITLE
Support string id in formatMessage as an alternative to full descriptor

### ISSUE THREAD

**Issue by ashmind** [formatjs/react-intl#1532]
**Is your feature request related to a problem? Please describe.**
In our project, we define message descriptions separately, and only use string ids to refer to them in code. This looks  like this
```
const x = intl.formatMessage({ id: 'xyz' });
```

The `{ id: }` part feels unnecessarily verbose.

**Describe the solution you'd like**
Add `formatMessage` overload that takes `id: string` instead of `descriptor: MessageDescriptor`.
The code above will be simplified to
```
const x = intl.formatMessage('xyz');
```

**Describe alternatives you've considered**
I could create a custom wrapper function to do that, but I would like people to learn `react.intl` instead of custom wrappers.

**Comment by longlho** [comment]
So it is unlikely that we'd support it because we actually encourage string declarations to co-exist with code due to several reasons:
- From what I've seen it helps engineers understand context better when strings are declared where they're used.
- String aggregation can pinpoint where they live (e.g our CLI output file name, line number, col number) so linguists/QA can update inline with high confidence of messing something up that's out of scope.

Separating strings out (potentially for reusability) isn't something we encourage since they are highly contextual.

**Comment by ConneXNL** [comment]
> * String aggregation can pinpoint where they live (e.g our CLI output file name, line number, col number) so linguists/QA can update inline with high confidence of messing something up that's out of scope.
> 
> Separating strings out (potentially for reusability) isn't something we encourage since they are highly contextual.

Read trough this comment twice but still don't understand what you are trying to say. It's probably me, but...

Isn't this really a matter of preference if someone would want to use formatMessage('id') instead of formatMessage({ id: 'id'})? There will always be arguments for both methods.

I was actually really suprised to see ;string' not working especially since nowadays many libraries have overloads and defaults to just make things as lean as possible.

In my case, 95% of the time I am just using id without options and I don't really want to think about the interface formatMessage's args wants me to use. Additionally, using an object makes the code look verbose and bound to a certain library where it really is just a string I want to transform.
