### ISSUE TITLE
defineMessages type does not enforce id and defaultMessage

### ISSUE THREAD

**Issue by steida** [formatjs/react-intl#1541]
But when missing, `intl.formatMessage` throws in runtime. That's suboptimal.

Is there any design consideration why props `id` and `defaultMessage` are nullable?

**Comment by longlho** [comment]
So there's a distinction between compile time & runtime here:

- `id` is required at runtime so we can lookup messages
- `id` is not required at compile time (which is when typechecking happen) because you can have compiler plugins (babel/typescript/webpack) that injects id in the distributed code.

Fortunately we can defer `id` enforcement to `eslint-plugin-formatjs` if u submit a feature request over at that repo
