### ISSUE TITLE
Wrong time format for en locale and 24h

### ISSUE THREAD

**Issue by yfr** [formatjs/react-intl#1577]
### Expected behavior

* I'll set the locale to `en-US` and the date format to `{hour12: false, hour: '2-digit'}` in the IntlProvider. 
* the formatted time for 30 minutes after midnight is `00:30`.

### Current behavior

* I'll set the locale to `en-US` and the date format to `{hour12: false, hour: '2-digit'}` in the IntlProvider. 
* the formatted time for 30 minutes after midnight is `24:30`.

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 3.4.0 |
|      `npm ls react` | 16.11.0 |
|     `npm --version` | 6.9.0 |
|    `node --version` | 13.8.0 |

| Browser | Version |
| ------- | ------- |
| Chrome    | 80.0.3987.87 |

**Comment by longlho** [comment]
what u're looking for is `hourCycle: 'h11'` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

**Comment by XavierLeTohic** [comment]
Similar issue for me, `hourCycle` seems to not being supported by the `FormattedTime` component event by using `formats` prop.

**Comment by lieut-data** [comment]
@longlho, do you have guidance for how to configure `hourCycle` with react-intl? If I'm tracing the code correctly, this is not a supported option to pass down and gets filtered out entirely: https://github.com/formatjs/react-intl/blob/1ec45cf4db91fe5523aa42c34bcd87a51a9ae245/src/formatters/dateTime.ts#L12-L28

So while I can use `hourCycle` with `Intl.DateTimeFormat` directly, I'm not sure how to achieve that with `react-intl` at present.

For additional context, I'm running into this because of https://bugs.chromium.org/p/chromium/issues/detail?id=1045791&q=hourcycle&can=1. It seems Chrome 80 recently started supporting the `hourCycle` field, and in turn started honouring the `en-US` locale configuration in this regard. But to the surprise of many, this configuration uses `[h12, h24]`, and results in the entirely unexpected `24:00` at midnight.

While the Chrome behaviour is technically correct, it's (currently) unique support for `hourCycle` makes it awkward to write clean code when other browsers which don't support `hourCycle` continue to render `00:00` at midnight. I'd love to find out who defines the locales and determine if this is a "bug", never before noticed since no one seems to have supported this field.

Anyway, would love you thoughts on all of this!

**Comment by longlho** [comment]
Ah that is indeed a bug on our side for not whitelisting `hourCycle`. The best way to determine if the behavior is correct is 2-fold:
- Check out cldr data set (e.g https://github.com/unicode-cldr/cldr-dates-full/tree/master/main/en-001)
- Try it out in ICU `DateTimeFormatter` yourself since all browsers use that.

**Comment by AceNorth** [comment]
@longlho Can you reopen this ticket? It appears to have been closed before it was discovered that it's a legitimate bug. I'm still running into it on the latest version
