### ISSUE TITLE
[FormattedMessage] Rich text nesting not working with multiple children

### ISSUE THREAD

**Issue by paul-v-m** [formatjs/react-intl#1598]
I'm updating from v3 to v4, moving from `FormattedHTMLMessage` to `FormattedMessage`. A couple of the messages have a `<ul>` with multiple `<li>`s. It works for a single `<li>`, but every after it doesn't get rendered.

### Expected behavior

The following should render a `ul` with two `li`s:

```
<FormattedMessage
  id="exampleMessage"
  defaultMessage="<ul><li>item1</li><li>item2</li></ul>" 
  values={{ 
    ul: msg => <ul>{msg}</ul>,
    li: msg => <li>{msg}</li>,
  }} />
```

### Current behavior

Only the first `li` is rendered

### codesandbox.io link to reproduce for BUG REPORT

https://codesandbox.io/s/reverent-wilbur-hf0id

### Your Environment

|          Executable | Version |
| ------------------: | :------ |
| `npm ls react-intl` | 4.1.1 |
|      `npm ls react` | 16.3.0 |
|     `npm --version` | 6.14.2 |
|    `node --version` | 13.3.0 |

**Comment by petersendidit** [comment]
The doc's have a good example of how this code should look: 
https://github.com/formatjs/react-intl/blob/master/docs/Components.md#rich-text-formatting

The problem is that the `ul` "function" gets passed multiple "chunks" which in this case are the two `li` elements.

If you use the [rest syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) then it should work correctly for you.
```jsx
<FormattedMessage
  id="exampleMessage"
  defaultMessage="<ul><li>item1</li><li>item2</li></ul>" 
  values={{ 
    ul: (...msg) => <ul>{msg}</ul>,
    li: (...msg) => <li>{msg}</li>,
  }} />
```

**Comment by paul-v-m** [comment]
Oh, that's fantastic. I missed that part of the documentation. Thanks, @petersendidit!

**Comment by longlho** [comment]
thanks @petersendidit!

**Comment by richard-lopes-ifood** [comment]
How to solve `key` warning on console?

```
    Warning: Each child in a list should have a unique "key" prop.
```

**Comment by longlho** [comment]
This has been fixed in the latest version
