### ISSUE TITLE
Disable the default message warning for fallback with region subtags

### ISSUE THREAD

**Issue by vdh** [formatjs/react-intl#356]
Related to #251.

```
[React Intl] Missing message: "table.no-data" for locale: "en-AU", using default message as fallback.
```

Can the missing message warning be disabled for region subtag fallback, or can there be some other way to indicate that a fallback from `en-AU`/`en-GB`/`en-US` back to `en` is an intended fallback?

Region subtags are essential for localising date formatting per region, and some phrases will require different translation text (colour vs color, etc.), but in most cases the `en-*` locales would ideally inherit  the majority of their messages from `en`.

Translations for non-English locales are planned in the future so a single-language app is not an option.

**Comment by ericf** [comment]
If your app's default locale is en-AU, then you can set it via the `defaultLocale` prop on `<IntlProvider>`

**Comment by vdh** [comment]
@ericf But the app's default locale is `en', not `en-AU`. What about translations for multiple regions? We can't release an app for `en-US` with a `defaultLocale` set to `en-AU`.

**Comment by ericf** [comment]
I think I see what you're saying now…

First, these warnings are only in development, and are not outputted in production.

Are your `en-AU` translations missing the `"table.no-data"` message? If so, my recommendation is to merge them with the default `en` translations before passing them into the `<IntlProvider>`.

**Comment by vdh** [comment]
So I originally thought I would end up with something like:

```
en.json // the bulk of english messages, extracted from defaultMessage strings
en-US.json // edge cases (e.g. color, USD currency)
en-AU.json // edge cases (e.g. colour, AUD currency)
en-GB.json // edge cases (e.g. colour, GBP currency)
// etc…
```

And I would set `defaultLocale` to `en` and then set `locale` per client (`en-US`/`en-GB`/`en-AU`/etc…), and then the translations would fall back to `en` if they were not covered by edge cases from the regional translations.


But if I'm understanding things correctly, I should instead do this:

1. In development, set a preferred `locale` and `defaultLocale` on `<IntlProvider>` (in my case, `en-AU`).
2. Write the `defaultMessage` strings in the region from step 1 (e.g. colour, AUD currency).
3. Extract these default translations using the babel plugin (`en-AU.json`).
4. Build the other regional translations by merging in the regional edge cases (e.g. color, USD for `en-US`) into the defaults extracted in step 3. Which creates:

```
en-AU.json // defaultMessage strings
en-GB.json // defaultMessage strings with overrides for edge cases (e.g. GBP replaces AUD)
en-US.json // defaultMessage strings with overrides for edge cases (e.g. color replaces colour, USD replaces AUD)
// etc…
```

5. Then in production, set the client's `locale` on `<IntlProvider>` depending on the client's preferred regional locale.

So then, the `defaultLocale` fallback would just go unused? Since each regional translation would contain duplicates from the `defaultMessage`?

**Comment by ericf** [comment]
Reopening this as a docs issue…

**Comment by ericf** [comment]
> Region subtags are essential for localising date formatting per region, and some phrases will require different translation text (colour vs color, etc.), _but in most cases the en-* locales would ideally inherit the majority of their messages from en._

Getting back to your original point — which I added emphasis — the problem is knowing when using a fallback message was intentional and when it's a mistake. If you had the following message: `"Today is {currentDate, date}"` the `currentDate` will be formatted according the to locale and a result like "2/3/2015" become ambiguous.

For this reason, I don't think it will be wise to remove the warning.

There's an open question here as to whether the `defaultMessage` should be formatted with the `defaultLocale` or the `locale`? Currently it will be formatted with the `defaultLocale`.

> So then, the defaultLocale fallback would just go unused? Since each regional translation would contain duplicates from the defaultMessage?

Yeah. And you could _only_ do this merging in development, and in production ship only the `en-AU` translations that differ from the default `en` strings since React Intl will automatically fallback — just be careful about the trap I mentioned above when messages have placeholders that will also contain formatted values like dates and numbers.
