### ISSUE TITLE
Examples with more than just english, and translation files

### ISSUE THREAD

**Issue by kosz** [formatjs/react-intl#461]
I was looking for an example that sets up i18n for anything other than english and shows how to create and setup translation files, but it looks like every example in the repo only sets up english and there are no translation files of any kind. 

Am I missing something ?

**Comment by steida** [comment]
You can check mine https://github.com/este/este dev stack, where react-intl is used in universal manner.

**Comment by ericf** [comment]
@kosz I only know English :) wanna translate the apps in the `/examples/` dir?

**Comment by kosz** [comment]
Thanks for your answers guys. I'll see if I can set some time aside for contributing as suggested :)

The most confusing thing for me was that there were no translation files. Perhaps splitting these words into their own translation files may look a bit more intuitive. At the end of the day, French doesn't have to be French for the example to be understood, normally we do things like 

fr-translation-file.js
```
{
  hello: '[FR] Hello',
  world: '[FR] word'
}

And this file is now ready for a non technical translator to work with easily

**Comment by Ognian** [comment]
Yes this is indeed the biggest disadvantage when trying to adopt this technology.
It took me more than a day to figure out that:
- I need the react-intl package
- and the babel-plugin-react-intl package
- which has to be added in the webpack (dev) config as a babel config
- and the react-intl-translations-manager package 
- which requires the babel-cli package
- and a script entry in the package.json
- which now requires the --preset es2015 option
- and an additional translationRunner.js script
- and that I should add the desired languages via addLocalData from react-intl/locale-data
- but when providing the locale and messages to IntlProvider it is my responsibility to choose the one and only correct message object

All of this is needed to correctly print "Hello World" or "Hallo Welt", which is the most trivial use case for everyone outside the us or uk. 

Documenting this is indeed the first step (thats why I wrote the above bullet list), but I see some additional issues too:
- the functionality of the babel-plugin-react-intl  and  react-intl-translations-manager  packages should be combined into the babel-plugin-react-intl package without requiring babel-cli
- instead of outputting a json file output an js file and add the description and additional information as comments  

Hopefully this comment helps until the docs are updated. I think that the approach choose with v2 where we can embed the default language into the code and make anything else and additional process is superior.
Thanks
Ognian

**Comment by steida** [comment]
@Ognian Instead of such a long whining you should send PR. Omg, what's wrong with those people? They can have awesome things for free, and instead of being happy they only cry that life is hard. Shame.

**Comment by Ognian** [comment]
@steida looks like you are a fan of the programming first and thinking thereafter approach. I prefer to discuss issues first. Answering a comment by begging for a PR or shaming people suggests a bad style.

**Comment by ericf** [comment]
addLocaleData is for low-level plural and relative-time formatting that's passed along to the lower-level libs React Intl is built on. The reason it's split out from the library is because loading the locale data for all languages would be expensive and wasteful since you only are running one language at a time. This stuff is documented: https://github.com/yahoo/react-intl/wiki#loading-locale-data

babel-plugin-react-intl is optional, you don't have to use it you use an external files to hold your default messages and translations. If you want to co-locate messages in your components, then you should use it to extract these strings into external files.

The reason you pass messages into IntlProvider is to setup the i18n context, this allows your app to be rendered as a function of props and state. And this is again, documented: https://github.com/yahoo/react-intl/wiki#creating-an-i18n-context

Yes it is going to be your responsibility to get your messages translated and pass them into the library. React Intl doesn't do translations, similarly React Intl doesn't negotiate the locale, you need to provide this as well. You could serialize the messages in the HTML page, or load them as a separate script, it's up to you for how ever it best integrates with your app.

The translations manager package is third-party and not something that I work on. So I can't speak about it other than it's not required to use React Intl.

**Comment by Ognian** [comment]
Thanks @ericf for the explanation. From a technical point of view I understand why babel-plugin-react-intl is optional, but from a framework user perspective when I'm searching for a i18n framework the translation workflow is the very first thing I'm looking at and everything else adds more and more value to the framework. Since I see that we don't have this yet lets try to build it, therefore my question would you accept a PR for babel-plugin-react-intl where functionality changes in that way that it generates not only the module files for a list of languages but also allows changes in those files to be preserved between runs? Or how would you proceed?

**Comment by steida** [comment]
@Ognian Check messages-extract.js and messages-check.js in https://github.com/este/este/tree/master/gulp

**Comment by ericf** [comment]
> therefore my question would you accept a PR for babel-plugin-react-intl where functionality changes in that way that it generates not only the module files for a list of languages but also allows changes in those files to be preserved between runs? Or how would you proceed?

@Ognian I don't fully understand what you're proposing here. The mental model is that babel-plugin-react-intl creates build artifacts based on the source, and what you do with those and how you integrate it into your translation pipeline is up to you. Many translation systems work differently, the idea is that the Babel plugin will provide you with the raw default strings, which then you can process and prep for translation.

**Comment by Ognian** [comment]
OK, the "workflow" I suggest is the following:

- Write your code in english using FormattedMessage. Lets assume we have only one Message in a js Module named ```TableOptions.js``` wich is in the ```containers```subdirectory of ```src```
```
 <FormattedMessage
                                        id="newItem"
                                        description="the text on the plus button for adding an item"
                                        defaultMessage="Add item"
                                    />
```  
- use the babel-plugin (i.e. react-intl). This plugin extracts the messages and prepares all the language files. Lets say we want to have german and french, then we would add the language option ```languages:[de fr]```and an option for an directory where to put the language files. This directory is treaded like a source code directory. Lets name this dir ``ì18n```. So for the above example we get 2 files ```TableOptions.de.json```and ```TableOptions.fr.json``` in ```i18n/containers```and the content of this files is for the first time running the plugin nearly the same:
```
[
  {
    "// id": "newItem",
    "// description": "the text on the plus button for adding an item",
    "// defaultMessage": "Add item",
    "newItem":"[DE] Add item"
  }
]
``` 
```
[
  {
    "// id": "newItem",
    "// description": "the text on the plus button for adding an item",
    "// defaultMessage": "Add item",
    "newItem":"[FR] Add item"
  }
]
``` 
- Now just using an editor you can edit and translate the files:
```
[
  {
    "// id": "newItem",
    "// description": "the text on the plus button for adding an item",
    "// defaultMessage": "Add item",
    "newItem":"Neuer Eintrag"
  }
]
``` 
```
[
  {
    "// id": "newItem",
    "// description": "the text on the plus button for adding an item",
    "// defaultMessage": "Add item",
    "newItem":"Nouvel élément"
  }
]
``` 
- When we rerun the babel plugin it first reads this language files. If a new id is found it is added as in step 2, if an id was deleted it is deleted too, and if an id was already in the file the translation is preserved  and the description and the default message are updated.
An important part is that the options for the babel plugin are NOT options of the plugin but options in the package.json of the app.

- We need a webpack plugin which collects all language files not only from our app but also from the modules in node_modules and generates the "optimal" (whatever this means) flatten file to be used as input to messages in IntlProvider. In the above example I showed a .json file where fields starting with ```//```should be treaded as comments and discarded by the webpack plugin. As I previously suggested we could use .js files instead i.e.:
```
lang=[
  {
    // id: newItem
    // description: the text on the plus button for adding an item
    // defaultMessage: Add item
    "newItem":"Neuer Eintrag"
  }
]
``` 
which I personally think is looking better (but this should be discussed)

 The reason for changing the workflow is that most of the applications are written AND translated by the developer(s) who normally knows at least 2 languages: his/her own and "bad english". "translation systems" can still be used and transform the ``ì18n```directory but my experience showed that a text editor is the best translation tool.

This workflow would also allow that modules added via npm bring their own translations.

**Comment by ericf** [comment]
@Ognian sounds like a **specific** workflow for your app, you should build that out. You have the tools to do so and nothing you described here couldn't be done by you writing a little bit of code to implement your desired workflow.

**Comment by Ognian** [comment]
After playing another day with memsource.com a web based CAT (Computer Aided Translation) Tool my eyes opend:
- generate a JSON File in the build directory (it can be discarded since it has NOT to preserve any previous translations). This JSON File has to contain an array of objects to translate. These objects can have as much keys as you want since they will be preserved in the translated output JSON File. It is only important that in one key we have the whole message to translate and in another key we can have a description wich is showed when translating this message.
- When we translate with the CAT Tool, a thing called Translation Memory TM is created which contains all the messages we translate and even more. This is the file which we save in the source directory together with the translated files and this is the file which enables the CAT Tool to "immediately" fill an newly generated file with the previously translated messages.

So how can we do this workflow:
- use babel-plugin-react-intl as it is and put the output into the build directory
- use a webpack plugin (is there already something like this?) to generate the one and only defaultMessages JSON File
- translate this file with a CAT Tool and get the translated result files(s) and the TM file which shall be saved somewhere in the source

What I'm still missing is:
- uniqueness of the id: actually only the uniqueness in one module can be assured. Maybe prepending the id with the path and the module name (name in package.json) would be a good idea, since actually we will have to load not only translated messages from our module but also some from node_modules too
- do you know of any simple and free CAT Tools? memsource.com looks good and they have a free option too. I also saw that okapi has such tools but haven't tried them out.

**Comment by ericf** [comment]
@Ognian You can write a simple node script (or create a Grunt, Gulp, etc. task) to aggregate the JSON files produced by babel-plugin-react-intl and apply your business logic; e.g., error on duplicate message ids.

I wrote code to do this for one of the example apps in this repo: https://github.com/yahoo/react-intl/blob/master/examples/translations/scripts/translate.js#L9-L26

**Comment by Ognian** [comment]
I wrote https://github.com/Ognian/reactIntlJson-loader a webpack loader to directly import the output of the translation:
```
import deMessages from 'reactIntlJson!./intl/TableOptions-en-de_at-C.json';

let messages = {};
messages.de = deMessages;
const currentLang = navigator.language
...
<IntlProvider locale={currentLang} messages={messages[currentLang]}>
...
```
and found https://github.com/danilobuerger/react-intl-loader/blob/master/index.js
another webpack loader which focuses on the conditional load so maybe we could even __chain__ both loaders (@danilobuerger)

@ericf thanks for the input, but I still have a problem with the react-intl babel plugin: it writes directly to the fs, which makes it write to the build directory even if webpack is in dev mode and actually uses a memory fs.
I searched a lot to find an example of a webpack loader or plugin to find a pattern how to do this without dumping to a directory but haven't been very successful.

**Comment by danilobuerger** [comment]
@Ognian most likely you can. If you have any trouble, open an issue in that repos and i will try to help out.

**Comment by ericf** [comment]
@Ognian please read through the babel plugin completely, because **it does** support providing the messages in memory and *only* writes to disk when the `messagesDir` option is provided. https://github.com/yahoo/babel-plugin-react-intl#via-node-api

**Comment by Ognian** [comment]
@ericf yes I saw it, thanks, I'm preparing a webpack plugin and a PR to babel-loader to pass thru metadata... Need just some more time to work on this... Will post back here

**Comment by Ognian** [comment]
@ericf the babel-loader pr is https://github.com/babel/babel-loader/pull/254
and the plugin https://github.com/Ognian/ReactIntlPlugin. I need some sleep before finishing and publishing the plugin ...

**Comment by Ognian** [comment]
Both are published now and should work
- https://github.com/Ognian/reactIntlJson-loader
- https://github.com/Ognian/react-intl-webpack-plugin

**Comment by jaredleechn** [comment]
@Ognian 👍

**Comment by SachaG** [comment]
I just wanted to add that I was also really confused by this (and still am). The first code snippet you see on the project's main page (`Hello <b>{name}</b>, you have…`) only contains hard-coded strings. Which seems strange for an i18n library?

**Comment by ericf** [comment]
@SachaG that should probably be changed. The idea was that the README could highlight that you might want to use this lib _even_ if your app is in one lang.

Anyone who wants to can submit a PR for a better README example.

**Comment by SachaG** [comment]
@ericf happy to do it once I finally figure out how to use this lib ;) The [previous library](https://github.com/TAPevents/tap-i18n) I was using was literally just `_("your_string_key")`, so there's a bit of a learning curve…

**Comment by JasonKleban** [comment]
I am also confused about how all the pieces are supposed to fit together.  Here's what I have so far:

src/messages.js:
```
import {defineMessages} from 'react-intl';

const messages = defineMessages({
    hello: {
        id: 'app.hello',
        description: 'Message to greet the user.',
        defaultMessage: 'Hello, {name}!'
    },
    goodbye: {
        id: 'app.goodbye',
        description: 'Message to dismiss the user.',
        defaultMessage: 'Goodbye, {name}!'
    }
}
```

src/components/my-component.js
```
    ...
    <FormattedMessage 
        id="app.my-message" 
        description="n Apple(s)"
        defaultMessage="{numOfApples, number} {numOfApples, plural, one {Apple} other {Apples}}" 
        values={{ numOfApples : data.numOfApples }} />
    ...
```

babel-plugin-react-intl seems to be configured correctly in .babelrc because I get:

dist/messages.json:
```
[
  {
    "id": "app.hello",
    "description": "Message to greet the user.",
    "defaultMessage": "Hello, {name}!"
  },
  {
    "id": "app.goodbye",
    "description": "Message to dismiss the user.",
    "defaultMessage": "Goodbye, {name}!"
  }
]
```

dist/components/my-component.json:
```
[
  {
    "id": "app.my-message",
    "description": "n Apple(s)",
    "defaultMessage": "{numOfApples, number} {numOfApples, plural, one {Apple} other {Apples}}" 
  },
  ...
]
```

And I have react-intl setup correctly I think:

```
<IntlProvider locale={theLocale} messages={???}>
    ...
</IntlProvider>
```

But I don't know what to put in the messages prop, because it wants an object with members indexed on the message id, but the json files are arrays of objects containing an ID instead.  Passing the json file data to defineMessages() seems to have no effect, so I don't think that's right.

```
type IntlConfig = {
    locale: string,
    formats: object,
    messages: {[id: string]: string},

    defaultLocale: string = 'en',
    defaultFormats: object = {},
};
```

1. How do we convert the json data file of messages to the format expected by IntlConfig?
2. Are we to manually create `messages.[culture].json` files (or some naming/organizational convention?) or is there some built-in feature?  Is there a prescribed convention for naming and organizing the per-culture translations?
3. What is the best practice for downloading to the client only the translation files needed for a particular culture?  Is there a built-in feature that does this automatically?
4. Once we have the necessary per-culture translation json files loaded, what is the recommended way to register them?  Do we combine them somehow?
5. Is there a way to refer to an already defined message by id in a `<FormatMessage />`?  I understand that we could refer to a single declaration of a `<FormatMessage />` by some predefined variable and reuse that, but I wouldn't want to reinvent a way of dealing with that across sourcecode .js files if a built-in feature for this already exists.

Thanks!

**Comment by Ognian** [comment]
@JasonKleban 
ad 1.) -> https://github.com/Ognian/reactIntlJson-loader
ad 2.) -> there are many different CAT Tools, I use memsource.com (the free version) and I'm trying to write my own tool too (but this will take some time), I'm using the file naming which comes from memsource.com
ad 3.) this  https://github.com/danilobuerger/react-intl-loader/blob/master/index.js should work by piping
with  reactIntlJson-loader, but I haven't tested it yet, since I have only 2 locals and I'm loading both...
ad. 5.) I asked myself this too, but came to the conclusion that this may be a "unwanted" feature. CAT Tools work already with the Translation Memory so entries with different key's but same message are "instantly" translated  ... thinking further someone could ask then why isn't the id then generated automatically

and maybe you would like to use https://github.com/Ognian/react-intl-webpack-plugin to combine all message files into one...

Hope this helps a little bit

**Comment by craigcosmo** [comment]
@Ognian why you need reactIntlJson-loader ? The json-loader on npm won't do the job for you?

**Comment by Ognian** [comment]
@craigcosmo translation tools, preserve the exact format.
So if the generated json file looks like:
```
[   {     "id": "cancelInHelp", 
         "defaultMessage": "Cancel"   },
    {     "id": "cancelInDetail",
     "defaultMessage": "Cancel"   },
   … 
  {     "id": "newItem", 
       "description": "the text on the plus button for adding an item", 
       "defaultMessage": "Add"   },   
…
  {     "id": "noActionsHeader",
        "defaultMessage": "no actions for {itemCount, plural, one {this item} other {those items}}"   } 
]
```
and the translated json file looks like:
**file A**
```
[   {     "id": "cancelInHelp",
          "defaultMessage": "Abbrechen"   },
     {     "id": "cancelInDetail",
          "defaultMessage": "Abbrechen"   },
   …  
    {     "id": "newItem", 
          "description": "the text on the plus button for adding an item", 
          "defaultMessage": "Hinzufügen"   }, 
  …   
     {     "id": "noActionsHeader", 
          "defaultMessage": "Keine Aktionen für {itemCount, plural, one{dieses Element} other{diese Elemente}}."   } 
]
```
then you need as an input to react inl  the translated file to look like:
**file B**
```
{     "cancelInHelp": "Abbrechen",
      "cancelInDetail": "Abbrechen",
       … 
       "newItem": "Hinzufügen",
       … 
    "noActionsHeader": "Keine Aktionen für {itemCount, plural, one{dieses Element} other{diese Elemente}}." }
```
reactInl-loader converts on the fly ***file A*** to look like **file B**, so it is not only a loader but also a converter...
you can also take a look at http://www.ogi-it.com/presentation/react_i18n.pdf
Ognian

**Comment by craigcosmo** [comment]
understand. But I was under impression that you are using `react-intl-translation-manager`, which generate file __B__ for you exactly how you desire file __B__ to be. 

Unless you are not using `react-intl-translation-manager` anymore.

**Comment by Ognian** [comment]
@craigcosmo no I'm not using  react-intl-translation-manager. I'm using Ognian/react-intl-webpack-plugin to create the combined messages json file from all modules (in the above example the file before file A) and then some translation service (in my case memsource) to translate the file ...

**Comment by randombumper** [comment]
Hi @Ognian, thanks for the plugins you wrote, they work great. This is a mite off-topic, but I didn't know where else to ask. I've been struggling to configure Memsource to parse the unified JSON file in a meaningful manner (importing only `defaultMessage`, with `description`as context). No matter what I put in the JSON config box, I get an empty list of strings to translate. Can you please help with that?

Thanks!

**Comment by Ognian** [comment]
take a look on page 14 of this pdf: http://www.ogi-it.com/presentation/react_i18n.pdf
Hope this helps...

**Comment by derwaldgeist** [comment]
+1

I'm new to React and tried to find out the best way to do i18n for a simple app. It's terribly hard to understand how the pieces fit together if there is no real-world samples actually using several languages (or, at least two of them). The uppercase English sample is more confusing than helpful. Besides this, I was looking for a good way to provide translation "on-the-fly", i.e. without reloading the whole page. When I was using MeteorJS, this was so simple. But with pure React, this seems to be quite hard to set-up.

It would be really great if there were samples showing a) how to use several languages and b) how to switch between them without server round-trips.

**Comment by craigcosmo** [comment]
@derwaldgeist yea it was very complicated to set it up. The examples suck. You have to go through all the example and about 50 other reading on the internet before you got an idea of how to put it together for real life usage. Then you need about a day to actually put it together. Here will save you sometime

I put a demo fully utilize react-intl in real world example
https://github.com/craigcosmo/demoapp

**Comment by derwaldgeist** [comment]
@craigcosmo Thanks a lot, will have a look at it!

**Comment by ericf** [comment]
@craigcosmo please feel free to contribute better examples to this repo. Instead of mentioning how the examples suck and how hard it is to use React Intl, it would be great if you helped make it better.

**Comment by sag1v** [comment]
@craigcosmo link is broken. would love to see a good example of implementing custom translations globally so other components can reuse it. as said before, all other examples out there are really not much of a help imho.

**Comment by NullVoxPopuli** [comment]
I think this library could learn from 
https://github.com/ember-intl/ember-intl

_much_ easier. :-\

**Comment by szimek** [comment]
Does anyone have an example of webpack (preferably 4.x) config that loads only locale data and messages for a given language? I'd like to avoid fetching them dynamically before the app is loaded or loading them for all languages, because of performance reasons. 

I guess I'll have to generate separate app bundle and html file for each language, but having an example would be really great.

BTW. Is this library still maintained? I'm using it in another project and really like it, but the latest commits are from April, but the last release was almost a year ago.

**Comment by NullVoxPopuli** [comment]
@szimek do you have to use this library? I've been finding react-18next to be quite easy

**Comment by szimek** [comment]
@NullVoxPopuli Thanks for the suggestion. I don't really have to, but I checked the docs some time ago and I prefer `react-intl` API ;)

Are there any examples like that for `react-i18next` though? I remember that the easiest way to use it was to use their XHR backend, but I'd prefer to limit number of requests before the app is loaded to show something as soon as possible.

**Comment by NullVoxPopuli** [comment]
i18next does the intl API :)
here is the project I'm currently working on https://github.com/sillsdev/appbuilder-portal/blob/master/source/SIL.AppBuilder.Portal.Frontend/src/translations/index.tsx 
(currently has local translations)

**Comment by szimek** [comment]
@NullVoxPopuli Thanks! I'll check it out.

**Comment by tricoder42** [comment]
@szimek In case you were interested, I'm working on https://github.com/lingui/js-lingui which is alternative to react-intl - it uses the same message syntax (MessageFormat), but is smaller, because message parsing/formatting is done offline. The API is also very similar, but optionally you can use babel-plugins for even simpler syntax. It also includes a CLI so you don't have to collect extracted messages by yourself.

There's an example of [webpack project](https://github.com/lingui/js-lingui/tree/master/examples/webpack-react) (only webpack 3 atm, though) which loads messages dynamically (one language per file) with locale data (plurals). 

Let me know if I can help. I was using react-intl before, so I also have some experinces with migrating project to jsLingui.

**Comment by redonkulus** [comment]
Good discussions, if anyone wants to make the docs better, please help out. Going to close this.
