### ISSUE TITLE
Alternative way to supply default messages?

### ISSUE THREAD

**Issue by tomdmaguire** [formatjs/react-intl#557]
Hi there,

In the [react-intl v2 changelog](https://github.com/yahoo/react-intl/issues/162) regarding the `IntlProvider` component, it states:

> Note: How there's no defaultMessages prop, that's because it's assumed the default message descriptors live co-located to where the messages are being formatted.

I currently am storing all translations as a json files (one file per locale e.g. en-US.json, de.json) which then are then loaded and passed into the `messages` prop of the IntlProvider.

Ideally I do not want to supply a `defaultMessage` prop each time I render a `FormattedMessage` component, as I have all of my "default messages" in a en-US.json translation file. (I always want to fallback to this locale).

To to cater for my scenario I built a wrapper for the `FormattedMessage` component which is basically as follows:

``` js
import { FormattedMessage } from 'react-intl';
const defaults = require('en-US.json');

export default function Translate({ id, ...values }) {
  return (
    <FormattedMessage id={id} values={values} defaultMessage={defaults[id]} />
  );
}
```

This works ok until I am in a situation where I cannot use the `Translate` React component and instead need to use the [inject api](https://github.com/yahoo/react-intl/wiki/API#injection-api), as then I have to duplicate the loading default messages logic (`defaultMessage={defaults[id]}`), in all places where I use the injected `intl` obj.

Do you have any examples of solutions I could use to overcome this duplication and simply use a message id in scenarios where I need to translate string and somehow fallback to en-US if the translation does not exist in the current locale?

Any help is much appreciated!
Thanks,
Tom

**Comment by ericf** [comment]
It's probably best if we add back the option to babel-plugin-react-intl to remove the extracted data. The issue was people were running the plugin multiple times by accident and getting errors. 

If you already have all of the default messages defined via the `defaultMessage` prop on FormattedMessage or using `defineMessages`, then you can omit providing the same messages to IntlProvider.

**Comment by tomdmaguire** [comment]
FYI, I eventually decided on the following method to handle locale fallbacks:

```js
import locales from 'lib/locales';

const messages = language === 'en' // english is our default locale
  ? locales['en']
  : merge({}, locales[language], locales['en']); 

return (
  <IntlProvider
    locale={language}
    messages={messages}
  >
    {children}
  </IntlProvider>
);
```

**Comment by derwaldgeist** [comment]
I'd like to support this enhancement. To me, having the default texts spread all over the source files is just not a good habit. In nearly all other i18n frameworks I've been using so far, you're just using keys and store your language-dependent strings completely outside your code. This allows you to adapt the default language easily. This is especially important if you're not a native English speaker, but want to use English as the default language. In this use-case, you typically will start to write your own en.json, but then hand it over to a professional English native speaker to adjust your texts.

**Comment by ericf** [comment]
@derwaldgeist you can currently use the approach you mentioned. Simply provide just an `id` prop to `<FormattedMessage>` and pass in your `messages` to `<IntlProvider>`

**Comment by derwaldgeist** [comment]
@ericf Thanks for your fast reply! That's the way I am already doing it. Problem is that you can't set default messages when instantiating the IntlProvider. I worked around this now by overloading the messages themselves using spread operators. So IntlProvider always gets a full message package, even if it consists of a mix of languages. Yet, it would be easier if IntlProvider could handle this internally instead of throwing exceptions if the FormatMessage itself does not contain a default.

**Comment by ericf** [comment]
> instead of throwing exceptions if the FormatMessage itself does not contain a default.

It doesn't throw exception, it logs warnings using `console.error` only in development. This is mainly as a safety for developers to know that the message formatting is having to fall back all the way to the message source or `id` value and outputting that in the UI — which is not ideal for users.

**Comment by khankuan** [comment]
@ericf, if the locale data already contains defaults, do you think it's a good idea to add an option to omit default messages in Babel for production?

**Comment by ericf** [comment]
I'm open to having an option for this for `babel-plugin-react-intl` for people to enable who are concerned about file size. The main reason to leave the default messages in the source by default is so the UI can fallback to something that doesn't depend on a network request (which is a common way people load locale data.)

**Comment by khankuan** [comment]
Fair enough. Thanks :)

**Comment by mauron85** [comment]
My concern with default translations is increased bundle size. Also the network argument is not very strong, as there many other ways how to provide default messages. IMHO it would be nice if `IntlProvider` have option to provide default messages and both sides will be happy.
Anyway @ericf was mentioning another option - removing default messages using `babel-plugin-react-intl`. What is the status of that?

**Comment by mauron85** [comment]
>FYI, I eventually decided on the following method to handle locale fallbacks:
@tomdmaguire so how does this work? Is react-inl automatically using EN as a fallback?

**Comment by tomdmaguire** [comment]
`merge({}, locales[language], locales['en'])` is where the "magic" is happening. I am simply merging the requested language obj with the EN obj, so the EN obj will fill in the gaps on un-translated content.

**Comment by mauron85** [comment]
@tomdmaguire so if react-intl is using EN messages as their default (fallback), then I'm actually quite happy and don't need anything more.
I will do the basically same thing you did. Load EN statically using webpack import, but other languages will be fetched in runtime (ajax or wepack ensure/require). Result will be merged same way.

**Comment by mauron85** [comment]
Regarding my comment about removing defineMessage block. If you using webpack I've found nice plugin https://www.npmjs.com/package/webpack-strip-block that seems to be suitable for this task. Just wrap your definitions with:

```
/* develblock:start */
defineMessages({
...
});
/* develblock:end */
```

Nice benefit is that your message definitions are still colocated with your class, but actually removed when compiling bundle.

**Comment by xotahal** [comment]
Hey guys, this is proposal, how we could solve this issue.

## Problem
I have these two js files (just example) with translations.

`en.js`
```js
{
    a-key: 'Message for A'
    b-key: 'Message for B'
}
```
`cs.js`
```js
{
    a-key: 'Translation for A'
}
```
You can see that the czech translation for `b-key` is missing. These two files I get from translation app. So I can't specify them in source code. Because our translators don't have access to source code to adjust the translations. They just sent me those translated files.

Then my `IntlProvider`:
```js
<IntlProvider
    defaultLocale="en"
    locale="cs"
    messages={messages["cs"]}
>
```
Now, when I use `formatMessage({ id: 'a-key' })` it returns `Translation for A` that is good. But when I use `formatMessage({ id: 'b-key' })` it returns 'b-key' on production.

Well, I know we can use `defaultMessage` to define default message and then the user would see that default message. But I think it's not good approach to have those messages mixed with source code.

## Solution

So I would create this pull request (super easy):

Add `defaultMessages` prop to `IntlProvider`:
```js
 <IntlProvider
    defaultLocale="en"
    locale="cs"
    messages={messages["cs"]}
    defaultMessages={messages["en"]}
>
```
Add 1 line and update 1 line in `formatMessage`:
```js
function formatMessage(config, state) {
  .....
  messages = config.messages,
  defaultMessages = config.defaultMessages, // <-- add this line
  ....
  
  var id = messageDescriptor.id;
  var defaultMessage =
               messageDescriptor.defaultMessage ||
               defaultMessages[id]; // <-- in this example it's b-key from en.json

   .....
```

**Comment by jianping-roth** [comment]
@xotahal when will your solution be available ?

**Comment by jpdevries** [comment]
I'm getting an error
`Message Descriptors require an id and defaultMessage` with

```js
  pluralChoose: {
    id: 'pluralChoose',
    defaultMessage: '', 
    one: 'item',
    other: 'items',
    few: 'items',
    many: 'items',
    zero: ''
  },
```

Is this a bug? Should it accept an empty `defaultMessage: ''`?

**Comment by tbarshchovskyi-vs** [comment]
The easiest solution to have some untranslated messages default to some other language is just always merge two sets of messages:

 ```
// Merged english messages with selected by user locale messages
 // In this case all data would be overridden to user selected locale, untranslated (missed in object)
 // keys just stay in english 
  const mergedMessages = Object.assign(messages['en'],messages[locale])

  return {
    defaultLocale: 'en',
    locale: locale,
    messages: mergedMessages
  }
```

**Comment by rasenplanscher** [comment]
For those of you looking for a default-locale feature:
Just do as @ericf has suggested several times already. Realize that you will have to provide the defaults anyway, and by merging beforehand, you will be set. Also, that way you can have any fallback strategy you like, e.g. going `de-AT -> de -> en` or `en-US -> en` depending on the current locale. That kind of thing is very simple on your end, but unnecessarily complex inside `react-intl`.

If you don't know how: `Object.assign` does that

@tbarshchovskyi-vs 
`Object.assign` actually mutates and returns the first parameter. That means, you overwrite data in `messages['en']`, and after your `assign`, this holds true: `mergedMessages === messages['en']`

**Comment by maxcc0** [comment]
@tomdmaguire How has your implementation of merging messages served you? I am in the same situation and planning to use this approach.

**Comment by teodors** [comment]
> That kind of thing is very simple on your end, but unnecessarily complex inside react-intl.

Can you please @rasenplanscher explain how this is complex for `react-intl`? Reading this issue it seems like an easy fix.

I find this incredibly frustrating that there is no default language fallback. How is it that 2 years have passed and there is still no "defaultMessages"? What is this if not lousy and lazy?

Merging works, but it is definitely a hacky way. What if said default "en" language gets updated, then you would have to re-merge every language. Depending on what sort of translation workflow one uses this could get "complex".

**Comment by rasenplanscher** [comment]
@teodors 
First of all, please refrain from calling the `react-intl` team, or anybody, lazy or their work lousy, that is just plain unkind and counter-productive. In fact, your post shows that you have not thought the issue through. If it's such an easy fix, please make a pull request and continue the discussion there. Do not assume that the `react-intl` team exists to accomplish what you are unable or unwilling to do. That would indeed be lazy and lousy.

Secondly, there is nothing hacky about providing your data in a way a service's interface requires. That's actually the normal state of affairs in my experience. You are correct that you need to re-merge on changes, but `react-intl` would need to do the exact same work, so your point is moot in this regard. Indeed, if you have your translations in git-managed files, there is a great advantage to doing the merging beforehand, so that the frontend would not even need to do any merging at all. On the other hand, if your translations are likely to be changed during the app's life-cycle, then you are probably in a very small minority and it would be economically terrible to tailor any **public library** (which `react-intl` is) to your **project-specific** needs.

Thirdly, as I already pointed out, if you do the merging, you are free to use any fallback strategy you desire. If `react-intl` were to support arbitrary fallback strategies, that would indeed become far more complex, and harder to maintain, than would be such maintenance on your end. Now, you might insist that `react-intl` could just stick with a simple strategy of exactly one fallback locale. That would indeed be relatively simple, but then again so would `Object.assign({},default,current)` on your end.

Additionally, if you had exactly this simple strategy, a lot of people would still be dissatisfied because of their more complex requirements and they would need to work around that – a case that you mention yourself. So, in order to arrive at a solution that makes most people happy, there would need to be a somewhat more involved strategy. That however would mean that, in simple cases `react-intl` would deliver much more code than necessary.

So, this should finally clear the issue in my view. Can we close this as `won't fix`? @tomdmaguire @ericf

**Comment by Chris-Petty** [comment]
I think this issue is going to keep getting bumped, as the way I see it defining "defaultMessage" in your `defineMessages` for most English speakers is just going to be their English translation anyway, so seems redundant (and presumingly they want to define it in one file).

Without looking into it, I'd assume that it shouldn't be big change adding a new `IntlProvider`prop "defaultMessages" to pair up with "defaultLocale" that is the source of default strings (presumably for that locale).

That way you can still get a nice message, like follows, just saying "using defaultMessages as fallback" instead.

![image](https://user-images.githubusercontent.com/7684221/41829506-463d4608-788f-11e8-8aad-0f43fb9ad1cc.png)

@rasenplanscher @ericf If that suggestion sounds agreeable I'm happy to have a crack at this if, using your repo knowledge, it's deemed not likely a massive PR in the making.

**Comment by rasenplanscher** [comment]
@Chris-Petty 
I do not have deep repo knowledge, so I'm not especially qualified. However, as can be seen in @xotahal's suggestion, with @jianping-roth's addition, that would be rather simple. My main issue is not that this in itself is bad, but that it invites a slippery slope of increasing complexity. See @ericf's and my previous messages on that.

Reading your message, my immediate thought was "what good is `defaultLocale`?" and indeed, I think I'd rather reduce the interface than adding new options. On account of legacy code, I'd depracate rather than remove, but still I think the whole defaulting work is best kept outside the library.

**Comment by abdulkadhir** [comment]
i got this error 
merge' is not defined  no-undef

**Comment by rasenplanscher** [comment]
@abdulkadhir 
I'm guessing you tried the previously proposed strategy involving `merge({}, locales[language], locales['en'])`.
Also, your error looks like an `eslint` error.

You need to provide a `merge` function. The easiest way would be to use `Object.assign` for this.

If you do that globally, as in the afforementioned example, you need to tell `eslint` about it by setting the `merge` variable in `globals`.
