### ISSUE TITLE
Number format masking

### ISSUE THREAD

**Issue by adrianblynch** [formatjs/react-intl#831]
I'm using the following to output a price:
```
<FormattedNumber
    currency="GBP"
    maximumFractionDigits={2}
    style="currency"
    value={99.50}
/>
```
Which results in:
```
<span>£99.50</span>
```
In some cases we'd like to keep the currency symbol, decimal and number of digits, but replace the digits with `*`. So:
```
<span>£**.**</span>
```
We'd like to keep the fact that the currency symbol can move and the decimal might change to a comma:
```
<span>**.**€</span>
```
Is there a way to do this with react-intl?

If not directly in react-intl, any work arounds anyone might know of?

Thanks.

**Comment by ericf** [comment]
React Intl leverages the `Intl.NumberFormat` API that's part of ECMAScript. This API only returns an opaque string and there's no alternate method to get a data structure.

To handle this problem, we developed a `formatToParts()` API that's been specified for the next version of ECMAScript you can see the details here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts (there's a similar one for `Intl.NumberFormat`).

We worked with the Firefox folks to develop this API and they are the first to implement it. So this is the long term solution to the problem you have.

Solutions that are viable to day involve parsing the formatted string. This means you'll need to have knowledge on the locales your app works within and the formatting options you're setting in order to correctly parse the string. If your app only needs to support a handful of locales, this is do-able; but if you want to support all of them the parsing required will be hard to get correct.
