### ISSUE TITLE
Input Field formatting

### ISSUE THREAD

**Issue by bryant988** [formatjs/react-intl#876]
We are using react with react-intl and need to write our own custom input fields. While it is possible to pass in a number to the react-intl API and get the number back properly formatted, how can we find out the current locale characters for things like thousand separators and decimal points? Or what is the best approach to handle input fields while leveraging from react-intl?

**Comment by bryant988** [comment]
Our requirements consist of only allowing valid input while the person is typing. 
So my issue is not about parsing the value _after_ it has been typed. 
It is more about restricting _while_ they type.

**Comment by ottrob** [comment]
Hi. I just wanted to ask if there are any new infos on this issue. We are facing the same problem. We also need to write our own custom input fields and want to use the react-intl package all over our application.
Our goal is it to have input fields which provide a live formatting. So for example our number input field should insert the thousand delimiters while typing. Because we use already the react-intl package to format our values, we would like to have access to all these characters like delimiters for a specific locale.
