### ISSUE TITLE
Rendering in <span>

### ISSUE THREAD

**Issue by ghost** [formatjs/react-intl#921]
It seems the translation always renders in a `<span>` element, can this be removed, so the text just renders stand-alone?

**Comment by ghostd** [comment]
Hi,

`FormattedMessage` has to wrap the translation. You can:
- change the tag used by FormattedMessage (see the [documentation](https://github.com/yahoo/react-intl/wiki/Components#formattedmessage))
- see previous issues about the same topic: #854, #513, #897 and other closed issues.

**Comment by bassbump** [comment]
It's just sucky for Buttons and <a>'s etc.

**Comment by kumarharsh** [comment]
@bassbump why is it sucky? Just want to know the reasoning. I also sometimes wish the same, but haven't felt a great urge (yet). because since `span` is an inline-element, it can nest infinitely within other inline elements with no loss of styling / functionality. It only 'looks' unnecessary, which I can live with.

**Comment by vinogradov** [comment]
Note for those who uses React Native: you can replace `span` to `Text` globally using 

`<IntlProvider locale=... messages=... textComponent={Text}>`

**Comment by e-e-e** [comment]
I think what your looking for is https://github.com/yahoo/react-intl/wiki/API#formatmessage

**Comment by redonkulus** [comment]
Closing as dup of https://github.com/formatjs/react-intl/issues/987
