### ISSUE TITLE
Use FormatNumber in Utils file outside Component

### ISSUE THREAD

**Issue by Jarory13** [formatjs/react-intl#926]
I'm wondering if it is yet possible use React-Intl APIs outside of the components. I have shared functionality that leverages formatNumber between three different files. I would like to move it a Utils file. I've seen 2 older posts (one from 2014 and one from 2016) that seemed to suggest this was an ongoing conversation. I was wondering if this has been resolved and if so how can I accomplish this?

**Comment by bmueller-sykes** [comment]
Just to add my .02 here, I completely agree. I've just started using this library, and I've run into 2 or 3 places already where I have translatable data sitting in plain old JS functions which reside in shared utility files, for example:
```
export const priorityOptions = () => {
  return [
    {value: 1, text: '1'},
    {value: 2, text: '2'},
    {value: 3, text: '3'},
  ]
}
```

What I really want to do is this:

```
export const priorityOptions = () => {
  return [
    {value: 1, text: formatNumber(1)},
    {value: 2, text: formatNumber(2)},
    {value: 3, text: formatNumber(3)},
  ]
}
```

...but I don't think `react-intl` supports that at the moment.

**Comment by bmueller-sykes** [comment]
After thinking about this over the weekend, my guess is that what we're asking for here will never happen, likely because by exporting functions like `formatNumber()`, they would be disconnected from the context of `IntlProvider`, which would render said functions somewhat useless (since `IntlProvider` tracks things like what the current language is, and so forth.

But that's just an educated guess.

**Comment by e-e-e** [comment]
In our app we just pass intl to the functions where we need them, either directly or through a function generator.

eg:
```js
const someFuncThatNeedsIntl = (intl) => (...args) => intl.formatNumber(...);
```

**Comment by bmueller-sykes** [comment]
@e-e-e but that function would need to be defined within a file that that has the IntlProvider context, like a file containing a React component, right? What I want is the ability to do translations in JS files that are completely disconnected from the React context, but then reference those functions within a React context. For example, if I wanted to do translations within a file that manages Redux state (those tend to be disconnected from the React context, but are then imported via `connect()` or whatever).

It may be that the right answer for this is to (sadly) abandon react-intl in favor of the underlying JS library, which would be something of a pain.

**Comment by Jarory13** [comment]
I suppose you could create a react context and do what @e-e-e is suggesting and export the functions from that file? It's just a theory, haven't tested it yet.

**Comment by e-e-e** [comment]
@bmueller-sykes that function does not need to be defined within a file that has the intl context, it just needs to be executed within a component with access to the intl content. By using a function generator, you can generate the function in a connected component and then pass (via prop) the returned function (now with intl context in its private scope) down to components that do not have intl injected.

Two examples: 

First using your code above would look like this:
```js 
// This is just pseudocode so please excuse errors
// const.js
export const priorityOptions = (intl) =>  [
    {value: 1, text: intl.formatNumber(1)},
    {value: 2, text: intl.formatNumber(2)},
    {value: 3, text: intl.formatNumber(3)},
  ];

// yourContainer.js
import { priorityOptions } from ‘const’;

const ConnectedComponent = (props) => {
  const { intl } = this.props;
  return (
    <Example options={priorityOptions(intl)} />
  );
}
```

Or if it's just the `text` property that needs the intl context, you could also provide text as a function in a similar way.

```js
export const priorityOptions = [
    {value: 1, text: intl => intl.formatNumber(1)},
    {value: 2, text: intl => intl.formatNumber(2)},
    {value: 3, text: intl => intl.formatNumber(3)},
  ];
```

This does not solve the issue of accessing intl within the redux reducer. I would argue that perhaps the impossibility of accessing intl in the reducer (outside context) suggests it might be an anti-pattern. Translation should probably occur in context. For example what happens if your app’s locale changes - your reducer could then hold translations from the old locale - or you have to retranslate everything again. On the other hand if your translations happen at the component level, then translations will only be executed when the values are displayed, and you risk no inconsistency.
