### ISSUE TITLE
How to call the formatMessage() to load the messages from the .json files  

### ISSUE THREAD

**Issue by PoojaSSW** [formatjs/react-intl#946]
I'm trying to call the formatMessage() API directly outside the comp w/o using the standard <FormattedMessage../> comp.
```
const locale = 'en';
const messages= defineMessages({
    greeting: {
        id: 'app.greeting',
        message:"some message",
        defaultMessage: 'Hello,all',
        description: 'Greeting to welcome the user to the app',
    }
  });
const { intl } = new IntlProvider({locale, messages}).getChildContext();
export function someFunc(key, values) {
   return intl.formatMessage({id:'greeting'});
}
```

well the above is static messages defined locally, however I have a translation files, en.json and ja.json globally stored that I would like to load the messages from.
How can I do that using the defineMessages, so that when I call the formatMessage() I should be able to see the messages from the resp files depending on the locale selected...

**Comment by ghostd** [comment]
Hi,

 i think you can llok at the 'async' example: https://github.com/yahoo/react-intl/blob/master/examples/async/index.js

**Comment by ericketts** [comment]
I second this, I'm a bit confused because the shape of the object coming out of `defineMessages` is not the shape of the object that you'd pass as `messages` on `IntlProvider`.

What if I want to use the object coming out of `defineMessages` with both `IntlMessageFormat` and `IntlProvider`? Do I have to manually massage the object coming out of `defineMessages`?
